/** 
Title: Rat Castle
Creators: Samson and Brycen
Description: You fight rats in a Castle

 */
// Setup game
scene.setTileMap(img`
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffeeeeffffffffffffffffffffffffffffffeeefffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffeeeffffffffffffeeeeeeeeee
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeeeeee
    eeeeeeeeffffffffeeeeeeeeeeeeeeeeeeeeeee44444444effffffeeeeeeeeee
    eeeeeeee44444444eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
`)
scene.setTile(14, img`
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        f f f f f f f f f f f f f f f f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        f f f f f f f f f f f f f f f f
    `, true)
scene.setTile(4, img`
        . . . 4 . . . 4 . . 4 . . . 4 4
        . 4 4 4 . 4 4 4 . 4 4 . . 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
    `)
info.setScore(0)
info.setLife(3)
// Setup character
let average_joe = sprites.create(img`
    ...........eeeeeee..............
    ..........eeeeeeeee.............
    ..........eeeeedddd.............
    ..........eeeeddddd.............
    ..........eededfddf.............
    ..........eeddddddd.............
    ..........eeddddddd.............
    ..........eeedddffd.......111111
    ...........eddddddd.......111111
    ............dddddd........11....
    ..........1111111111ddddddddd...
    ..........1111111111ddddddddd...
    ..........1111111111......dd....
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    .........ddd888888..............
    .........ddd888.88..............
    .........ddd888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............eee.eee.............
    ............eeeeeeee............
`)
controller.moveSprite(average_joe, 90, 0)
average_joe.setPosition(15, 75)
scene.cameraFollowSprite(average_joe)
controller.A.onEvent(ControllerButtonEvent.Pressed, function on_event_pressed() {
    average_joe.vy = -150
})
average_joe.ay = 200
average_joe.setKind(SpriteKind.Player)
// Make gun
controller.B.onEvent(ControllerButtonEvent.Pressed, function on_event_pressed2() {
    let projectile = sprites.createProjectileFromSprite(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..............111...............
    .............11111..............
    .............11111..............
    .............11111..............
    ..............111...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, average_joe, 200, 0)
})
// Make enemies
let rat = sprites.create(img`
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
`)
rat.setPosition(300, 80)
rat.setKind(SpriteKind.Enemy)
rat.ay = 150
let rat2 = sprites.create(img`
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
`)
rat2.setPosition(400, 80)
rat2.setKind(SpriteKind.Enemy)
rat2.ay = 150
let rat3 = sprites.create(img`
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
`)
rat3.setPosition(500, 80)
rat3.setKind(SpriteKind.Enemy)
rat3.ay = 150
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function on_overlap(sprite: Sprite, otherSprite: Sprite) {
    sprite.destroy()
    otherSprite.destroy()
    info.changeScoreBy(1)
})
// Make lava work
scene.onHitTile(SpriteKind.Player, 4, function on_hit_tile(sprite: Sprite) {
    average_joe.destroy()
})
// Make rats kill joe
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function on_overlap2(sprite: Sprite, otherSprite: Sprite) {
    info.changeLifeBy(-1)
})
