"""
Title: Rat Castle
Creators: Samson and Brycen
Description: You fight rats in a Castle
"""
#Setup game
scene.set_tile_map(img("""
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffeeeeffffffffffffffffffffffffffffffeeefffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffeeeffffffffffffeeeeeeeeee
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffeeeeeeeeee
    eeeeeeeeffffffffeeeeeeeeeeeeeeeeeeeeeee44444444effffffeeeeeeeeee
    eeeeeeee44444444eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
"""))
scene.set_tile(14,
    img("""
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        f f f f f f f f f f f f f f f f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        b b b b b b b f b b b b b b b f
        f f f f f f f f f f f f f f f f
    """),
    True)
scene.set_tile(4,
    img("""
        . . . 4 . . . 4 . . 4 . . . 4 4
        . 4 4 4 . 4 4 4 . 4 4 . . 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4
        4 4 4 4 4 4 4 5 4 4 4 4 4 2 2 4
        4 4 4 4 4 4 4 4 5 5 4 4 4 4 2 4
        4 4 4 5 5 5 4 4 4 5 5 4 4 4 2 4
        4 4 5 5 4 5 4 4 4 4 5 5 4 4 4 2
        4 5 4 4 4 5 5 4 4 4 4 5 5 4 4 4
        4 4 4 4 4 4 5 5 5 5 5 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 5 4 4 4 4 4
        2 2 4 4 4 4 4 4 4 4 5 5 4 4 4 4
        4 2 2 4 4 4 4 4 4 4 4 5 5 5 5 4
        4 4 4 2 2 2 2 4 4 4 4 4 4 4 4 4
        4 5 4 4 4 4 4 2 4 4 4 4 4 4 4 4
        4 4 5 5 4 4 4 2 2 2 4 4 4 4 4 4
        4 4 4 4 5 5 5 4 4 2 2 4 4 4 4 4
    """),
    )
#Setup character
average_joe = sprites.create(img("""
    ...........eeeeeee..............
    ..........eeeeeeeee.............
    ..........eeeeedddd.............
    ..........eeeeddddd.............
    ..........eededfddf.............
    ..........eeddddddd.............
    ..........eeddddddd.............
    ..........eeedddffd.......111111
    ...........eddddddd.......111111
    ............dddddd........11....
    ..........1111111111ddddddddd...
    ..........1111111111ddddddddd...
    ..........1111111111......dd....
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    .........ddd888888..............
    .........ddd888.88..............
    .........ddd888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............eee.eee.............
    ............eeeeeeee............
"""))
controller.move_sprite(average_joe, 75, 0)
average_joe.set_position(15, 75)
scene.camera_follow_sprite(average_joe)
def on_event_pressed():
    average_joe.vy = -125
controller.A.on_event(ControllerButtonEvent.PRESSED, on_event_pressed)
average_joe.ay = 150
average_joe.set_kind(SpriteKind.player)

#Make gun
def on_event_pressed2():
    projectile = sprites.create_projectile_from_sprite(img("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..............111...............
    .............11111..............
    .............11111..............
    .............11111..............
    ..............111...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """), average_joe, 50, 0)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_event_pressed2)


#Make enemies
rat = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat.set_position(300, 80)
rat.set_kind(SpriteKind.enemy)
rat.ay = 150

rat2 = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat2.set_position(400, 80)
rat2.set_kind(SpriteKind.enemy)
rat2.ay = 150

rat3 = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat3.set_position(500, 80)
rat3.set_kind(SpriteKind.enemy)
rat3.ay = 150

def on_overlap(sprite, otherSprite):
    sprite.destroy()
    otherSprite.destroy()
sprites.on_overlap(SpriteKind.enemy, SpriteKind.projectile, on_overlap)

#Make lava work
def on_hit_tile(sprite):
    average_joe.destroy()
scene.on_hit_tile(SpriteKind.player, 4, on_hit_tile)