"""
Title: Rat Castle
Creators: Samson and Brycen
Description: You fight rats in a Castle
"""
#Setup game
scene.set_tile_map(img("""
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeeeeee.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.eeeef.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.feeee.ff.ff.ff.ff.ff.ff.ff.ff.feeef.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ffeee
    ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.ff.feeeeeee
    eeeeeeee.ff.ff.f22eeeeeeeeeeeeeeeeeee33ff.ff.ff.ff.ff.ff.ff.ff.ef.ff.ff.feeeeeee
    eeeeeeee44444444eeeeeeeeeeeeeeeeeeeeeee444444444444444444444444eeeeeeeeeeeeeeeee
"""))
scene.set_background_image(img("""
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff1111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffff11111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffff1111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff1111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffff11111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffff1111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffff1ffffffffffff1111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffff111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff11111111111111111111111111111111111ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffff
    ffffffffffffffffff1111111dddddd111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff111111ddddddd1111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff111111dddddddd1111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111ddddddd1111111111111111dd11111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111ddddddd111111111111ddddddd1111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111ddddddd11111111111ddddddddd1111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111dddddd111111111111ddddddddd1111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff11111111111111111111111111dddddddd11111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff111111111111111111111111111ddddddd11111111fffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111dddddd11111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff1111111111111111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1111111111111111111dddddd11111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff111111111111111111ddddddd11111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff1111111111111111ddddddddd1111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffff111111111111111dddddddddd111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffff111111111111111ddddddddd111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffff111111111111111dddddddd111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffff
    fffffffffffffffffffffff111111111111111ddddddd111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff111111111111111ddddd111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff11111111111111111111111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffff111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffff11111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffff11111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffff111111111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
    7777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
"""))
scene.set_tile(14,
    img("""
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        b b b b b b b b b b b b b b b f
        f f f f f f f f f f f f f f f f
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        b b b b b b b f b b b b b b b b
        f f f f f f f f f f f f f f f f
    """),
    True)
scene.set_tile(4,
    img("""
        . . . 4 . . . 4 . . 4 . . . 4 4
        . 4 4 4 . 4 4 4 . 4 4 . . 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
    """),
    True)
scene.set_tile(15, img("""
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    c c c c c c c c c c c c c c c f
    f f f f f f f f f f f f f f f f
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    c c c c c c c f c c c c c c c c
    f f f f f f f f f f f f f f f f
"""))
scene.set_tile(2, img("""
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    f f f f f f f f f f f f f f f f
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    f f f f f f f f f f f f f f f f
"""), True)
scene.set_tile(3, img("""
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    b b b b b b b b b b b b b b b f
    f f f f f f f f f f f f f f f f
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    b b b b b b b f b b b b b b b b
    f f f f f f f f f f f f f f f f
"""), True)
info.set_score(0)
info.set_life(1)

#Setup character
average_joe = sprites.create(img("""
    ...........eeeeeee..............
    ..........eeeeeeeee.............
    ..........eeeeedddd.............
    ..........ee1eddddd.............
    ..........e1d1dfddf.............
    ..........e1d1ddddd.............
    ..........e1dd99999.............
    ..........ee1d99999.......111111
    ...........e1d99999.......111111
    ............d199999.......11....
    ..........1111111111ddddddddd...
    ..........1111111111ddddddddd...
    ..........1111111111......dd....
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    ..........dd111111..............
    .........ddd888888..............
    .........ddd888888..............
    .........ddd888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............888.88..............
    ............eee.eee.............
    ............eeeeeeee............
"""))
controller.move_sprite(average_joe, 100, 0)
average_joe.set_position(15, 260)
scene.camera_follow_sprite(average_joe)
average_joe.set_kind(SpriteKind.player)
def on_hit_tile2(sprite):
    average_joe.set_image(img("""
        ...........eeeeeee..............
        ..........eeeeeeeee.............
        ..........eeeeedddd.............
        ..........ee1eddddd.............
        ..........e1d1dfddf.............
        ..........e1d1ddddd.............
        ..........e1dd99999.............
        ..........ee1d99999.......111111
        ...........e1d99999.......111111
        ............d199999.......11....
        ..........1111111111ddddddddd...
        ..........1111111111ddddddddd...
        ..........1111111111......dd....
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        .........ddd888888..............
        .........ddd888888..............
        .........ddd888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............eee.eee.............
        ............eeeeeeee............
    """))
scene.on_hit_tile(SpriteKind.player, 14, on_hit_tile2)
average_joe.ay = 250

#Make gun
def on_shoot():
    def on_throttle():
        projectile = sprites.create_projectile_from_sprite(img("""
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ......................................................555.......
        .....................................................55555......
        .....................................................55555......
        .....................................................55555......
        ......................................................555.......
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        """), average_joe, 500, 0)
        average_joe.set_image(img("""
        ...........eeeeeee..............
        ..........eeeeeeeee.............
        ..........eeeeedddd.............
        ..........ee1eddddd.............
        ..........e1d1dfddf.............
        ..........e1d1ddddd.............
        ..........e1dd99999.............
        ..........ee1d99999.......111111
        ...........e1d99999.......111111
        ............d199999.......11....
        ..........1111111111ddddddddd...
        ..........1111111111ddddddddd...
        ..........1111111111......dd....
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        .........ddd888888..............
        .........ddd888888..............
        .........ddd888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............888.88..............
        ............eee.eee.............
        ............eeeeeeee............
        """))
    timer.throttle("action", 1000, on_throttle)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_shoot)

#Make enemies
rat = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat.set_position(350, 190)
rat.set_kind(SpriteKind.enemy)
rat.ay = 150

rat2 = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat2.set_position(450, 190)
rat2.set_kind(SpriteKind.enemy)
rat2.ay = 150

rat3 = sprites.create(img("""
    ................................
    ................................
    ................................
    .......eeeee.......eeee.........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee.....eeeeee........
    ......eeeeeee..eeeeeeeee........
    .......eeeeeeeeeeeeeeeee........
    ........eeeeeeeeeeeeeeee........
    ..........eeeeeeeeeeee..........
    ..........efeeeefeeee...........
    ..........efeeeefeeee...........
    .....eeddddddddddddee...........
    ......eddddddddddddee...........
    ........ddddddddddde............
    .........dddddddddd.............
    ..........eedddde...............
    .........eedddddeee.............
    ........eeeddddddeeee...........
    .......e.edddddddde.ee..........
    ......e..edddddddde..e.....e....
    .....ee..edddddddde..e..eeee....
    ....ee...edddddddde..e.ee.......
    ....e....edddddddeee...e........
    .........eeeeeeeee..eeee........
    ..........eee.eeee..............
    ..........eee.eeee..............
    ..........eee.eeee..............
    .........eeee.eeeee.............
    ........eeeee..eeee.............
    ........eeeee..eeee.............
"""))
rat3.set_position(550, 190)
rat3.set_kind(SpriteKind.enemy)
rat3.ay = 150

def on_overlap(sprite, otherSprite):
    sprite.destroy()
    otherSprite.destroy()
    info.change_score_by(5)
    music.ba_ding.play()
sprites.on_overlap(SpriteKind.enemy, SpriteKind.projectile, on_overlap)

#Make lava work
def on_hit_tile(sprite):
    info.change_life_by(-1)
    game.splash("You tried to swim in lava!?")
scene.on_hit_tile(SpriteKind.player, 4, on_hit_tile)

#Make rats kill joe
def on_overlap2(sprite, otherSprite):
    info.change_life_by(-1)
    game.splash("You suck!")
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_overlap2)

#Make giant rat
giant_rat = sprites.create(img("""
    ....................eeee.........eeeeeee........................
    .................eeeeeeeee......eeeeeeeee.......................
    ................eeeeeeeeeee.....eeeeeeeee.......................
    ................eeeeeeeeeee.....eeeeeeeee.......................
    ................eeeeeeeeeee.....eeeeeeeee.......................
    .................eeeeeeeeee......eeeeeeee.......................
    .................eeeeeeeeeeeeeeeeeeeeeeee.......................
    ..................eeeeeeeeeeeeeeeeeeeeeee.......................
    ..................eeeeeeeeeeeeeeeeeeeeee........................
    ....................eeeefeeeeeeeeefeeee.........................
    ......................eeeffeeeeeffeeeee.........................
    ......................eeeeefeeefeeeeeee.........................
    ......................eeeefeeeeffeeeeee.........................
    .......................effeeeeeeeffeeee.........................
    .......................eeeeeeeeeeeeeeee.........................
    .................eeedddddddddddddddddee.........................
    ..................eeddddddddddddddddde..........................
    ..................7eddddd1f1f1f1ddddd...........................
    .................77.ddddfffffffffdd.............................
    .................777..dd1f1f1f1f1d..............................
    .................7.7.eeeeeeeeeeeeeeeeee.........................
    ..................eeeeeeeddddddddddeeeeeee......................
    ................eeeeeeeeddddddddddddeeeeeeee....................
    ...............eeeeeeeedddddddddddddeeeeeeeeee..................
    .............eeeeeeeeedddddddddddddddeeeeeeeeee.................
    ............eeeeeeeeedddddddddddddddddeeeeeeeeeee...............
    ...........eeeeeeeeedddddddddddddddddddeeeeeeeeeee..............
    ..........eeeeeeeeeedddddddddddddddddddeeeeeeeeeeee.............
    .........eeeeeeeeeeeddddddddddddddddddddeeeeeeeeeee.............
    ........eeeeeeeeeeedddddddddddddddddddddeeeeeeeeeeee............
    .......eeeeeeeeeeeeddddddddddddddddddddddeeeeeeeeeee............
    .......eeeeeeeeeeedddddddddddddddddddddddeeeeeeeeeeee...........
    ......eeeeeeeeeeeeddddddddddddddddddddddddeeeeeeeeeee...........
    .....eeeeeeeeeeeedddddddddddddddddddddddddeeeeeeeeeeee..........
    .....eeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeee..........
    ....eeeeeeeeeeeedddddddddddddddddddddddddddeeeeeeeeeee..........
    ....eeeeeeeeeeeedddddddddddddddddddddddddddeeeeeeeeeee........e.
    ....eeeeeeeeeeeedddddddddddddddddddddddddddeeeeeeeeeee.......e..
    ....eeeeeeeeeeeedddddddddddddddddddddddddddeeeeeeeeeeee......e..
    ....eeeeeeeeeeedddddddddddddddddddddddddddde.eeeeeeeeee......e..
    ....eeeeeeeeeeedddddddddddddddddddddddddddde.eeeeeeeeee......e..
    ....eeeeeeeeeeedddddddddddddddddddddddddddde.eeeeeeeeee......e..
    .....eeeeeeee.edddddddddddddddddddddddddddde.eeeeeeeeee......e..
    .....eeeeeeee.eeddddddddddddddddddddddddddde..eeeeeeeeee.....e..
    .....eeeeeee...eedddddddddddddddddddddddddde..eeeeeeeeee.....e..
    ......eeeeee.....eddddddddddddddddddddddddee...eeeeeeeee.....e..
    .......eeee.....eeeddddddddddddddddddddddeee...eeeeeeeee.....e..
    .................eeeddddddddddddddddddddeee.....eeeeeeee.....e..
    .................eeeeeddddddddddddddddeeeeee.....eeeeeee.....e..
    ..................eeeeeeeedddddddddddeeeeeee.....eeeeee.....ee..
    ..................eeeeeeeeeeeeeeeeeeeeeeee..e....eeeee.....e....
    ..................eeeeeeeee......eeeeeeeee...ee..........ee.....
    ..................eeeeeeeee......eeeeeeeee.....eee....eee.......
    ..................eeeeeeeee......eeeeeeeee.......eeeee..........
    ..................eeeeeeeee......eeeeeeeee......................
    ..................eeeeeeeee......eeeeeeeee......................
    ..................eeeeeeeee......eeeeeeeee......................
    .................eeeeeeeeee......eeeeeeeeee.....................
    .................eeeeeeeeee......eeeeeeeeeee....................
    ................eeeeeeeeeee......eeeeeeeeeeee...................
    ...............eeeeeeeeeee........eeeeeeeeeee...................
    ..............eeeeeeeeeeee........eeeeeeeeeeee..................
    .............eeeeeeeeeeeee.........eeeeeeeeeeeee................
    ............eeeeeeeeeeeee...........eeeeeeeeeeee................
"""))
giant_rat.set_position(1200, 200)
cough = sprites.create_projectile_from_sprite(img("""
     ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .....11.........................................................
        ...11111.11111..................................................
        ..1111111111111.................................................
        ..11111111111111................................................
        ..1111111111111.................................................
        ..11111111111111................................................
        ..111111111111111...............................................
        .1111111111111111...............................................
        11111111111111111...............................................
        111111111111111111..............................................
        111111111111111111..............................................
        .11111111...11111...............................................
        .1111111........................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
"""), giant_rat, -50, 50)
def on_destroyed(sprite):
    projectile = sprites.create_projectile_from_sprite(img("""
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .....11.........................................................
        ...11111.11111..................................................
        ..1111111111111.................................................
        ..11111111111111................................................
        ..1111111111111.................................................
        ..11111111111111................................................
        ..111111111111111...............................................
        .1111111111111111...............................................
        11111111111111111...............................................
        111111111111111111..............................................
        111111111111111111..............................................
        .11111111...11111...............................................
        .1111111........................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
    """), giant_rat, -50, 50)
sprites.on_destroyed(SpriteKind.projectile, on_destroyed)
giant_rat.set_kind(SpriteKind.food)
def on_overlap5(sprite, otherSprite):
    info.player1.change_life_by(-1)
    game.splash("You suck!")
sprites.on_overlap(SpriteKind.player, SpriteKind.food, on_overlap5)
giant_rat.ay = 500

#Make cough kill joe
def on_overlap3(sprite, otherSprite):
    info.change_life_by(-1)
    game.splash("Don't you know? Corona kills.")
sprites.on_overlap(SpriteKind.player, SpriteKind.projectile, on_overlap3)
def on_destroyed2(sprite):
    average_joe.set_position(15, 190)
sprites.on_destroyed(SpriteKind.player, on_destroyed2)

#Make time limited
info.start_countdown(25)

#make title screen
game.splash("Rat Castle: 'The princess is in another castle.'")

#Make big rat die
def on_overlap4(sprite, otherSprite):
    giant_rat.destroy()
    info.change_score_by(20)
    music.ba_ding.play()
    game.over(True)
sprites.on_overlap(SpriteKind.food, SpriteKind.projectile, on_overlap4)

#make enemies move
rat.set_velocity(-75, 0)
rat2.set_velocity(-75, 0)
rat3.set_velocity(-75, 0)
def on_hit_tile3(sprite):
    rat.set_velocity(75, 0)
    rat2.set_velocity(75, 0)
    rat3.set_velocity(75, 0)
scene.on_hit_tile(SpriteKind.enemy, 2, on_hit_tile3)

def on_hit_tile4(sprite):
    rat.set_velocity(-75, 0)
    rat2.set_velocity(-75, 0)
    rat3.set_velocity(-75, 0)
scene.on_hit_tile(SpriteKind.enemy, 3, on_hit_tile4)

#Make jump
jump = True
def on_event_pressed():
    global jump
    if jump:
        average_joe.set_velocity(0, -150)
        average_joe.set_image(img("""
        ...........eeeeeee..111.........
        ..........eeeeeeeee.111.........
        ..........eeeeedddd.111.........
        ..........ee1eddddd.111..dd.....
        ..........e1d1dfddf.1111dddd....
        ..........e1d1ddddd.1111dddd....
        ..........e1dd99999......dd.....
        ..........ee1d99999......dd.....
        ...........e1d99999......dd.....
        ............d199999......dd.....
        ..........1111111111ddddddd.....
        ..........1111111111ddddddd.....
        ..........1111111111............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        ..........dd111111..............
        .........ddd8888888.............
        .........ddd888888888...........
        .....eeeeddd88888888888.........
        ....eee888.88888.888888.........
        ...eee8888888888..88888.........
        ..eeee8888888888...8888.........
        ..eeee.88888888.....888.........
        ..eeee...88888......888.........
        ...ee.....888.......888.........
        ....................eeee........
        ....................eeeeee......
        ....................eeeeee......
        """))
        jump = average_joe.is_hitting_tile(CollisionDirection.BOTTOM)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_event_pressed)
def on_update():
    global jump
    if average_joe.is_hitting_tile(CollisionDirection.BOTTOM):
        jump = True
game.on_update(on_update)
